spring:
  application:
    name: prescription-service
  datasource:
    url: jdbc:mysql://localhost:3306/prescription_service
    username: root
    password: root1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
  kafka:
    bootstrap-servers: localhost:9193  # địa chỉ Kafka broker
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 5007
  error:
    include-stacktrace: never

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#jwt:
#  expiration: 2592000
#  expiration-refresh-token: 5184000
#  secretkey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
#
#api:
#  prefix: /api/v1


