server:
  port: 8888
  error:
    include-stacktrace: never

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:5004
          predicates:
            - Path=${app.api-prefix}/auth/**
          filters:
            - StripPrefix=2

        - id: user-service
          uri: http://localhost:5004
          predicates:
            - Path=${app.api-prefix}/admin/users/**, ${app.api-prefix}/users/**
          filters:
            - StripPrefix=2

        - id: account-service
          uri: http://localhost:5004
          predicates:
            - Path=${app.api-prefix}/account/**
          filters:
            - StripPrefix=2

        - id: permission-service
          uri: http://localhost:5004
          predicates:
            - Path=${app.api-prefix}/admin/permissions/**
          filters:
            - StripPrefix=2

        - id: role-service
          uri: http://localhost:5004
          predicates:
            - Path=${app.api-prefix}/admin/roles/**
          filters:
            - StripPrefix=2

        - id: notification-service
          uri: http://localhost:5004
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2

        - id: file-service
          uri: http://localhost:5004
          predicates:
            - Path=${app.api-prefix}/internal/files/**
          filters:
            - StripPrefix=2


        - id: medicine-service
          uri: http://localhost:5005
          predicates:
            - Path=${app.api-prefix}/medicines/**, ${app.api-prefix}/admin/medicines/**
          filters:
            - StripPrefix=2

        - id: medicineWarehouse-service
          uri: http://localhost:5005
          predicates:
            - Path=${app.api-prefix}/admin/medicine-warehouse/**
          filters:
            - StripPrefix=2

        - id: category-service
          uri: http://localhost:5005
          predicates:
            - Path=${app.api-prefix}/categories/**, ${app.api-prefix}/admin/categories/**
          filters:
            - StripPrefix=2
        - id: dosage-service
          uri: http://localhost:5005
          predicates:
           - Path= ${app.api-prefix}/dosage-forms/**, ${app.api-prefix}/admin/dosage-forms/**
          filters:
           - StripPrefix=2


        - id: file-service
          uri: http://localhost:5005
          predicates:
            - Path=${app.api-prefix}/files/**
          filters:
            - StripPrefix=2

        - id: doctor-service
          uri: http://localhost:5006
          predicates:
            - Path=${app.api-prefix}/doctors/** ,${app.api-prefix}/admin/doctors/**
          filters:
            - StripPrefix=2

        - id: file-service
          uri: http://localhost:5006
          predicates:
            - Path=${app.api-prefix}/files/**
          filters:
            - StripPrefix=2

        - id: department-service
          uri: http://localhost:5007
          predicates:
            - Path=${app.api-prefix}/admin/departments/**
          filters:
            - StripPrefix=2

        - id: room-service
          uri: http://localhost:5007
          predicates:
            - Path=${app.api-prefix}/admin/rooms/**
          filters:
            - StripPrefix=2

        - id: appointment-service
          uri: http://localhost:5008
          predicates:
            - Path=${app.api-prefix}/appointments/**
          filters:
            - StripPrefix=2


        - id: patient-service
          uri: http://localhost:5009
          predicates:
            - Path=${app.api-prefix}/patients/**
          filters:
            - StripPrefix=2

        - id: prescription-service
          uri: http://localhost:5010
          predicates:
            - Path=${app.api-prefix}/prescriptions/**
          filters:
            - StripPrefix=2