server:
  port: 8888
  error:
    include-stacktrace: never

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:5004
          predicates:
            - Path=${app.api-prefix}/auth/**
          filters:
            - StripPrefix=2

        - id: user-service
          uri: http://localhost:5004
          predicates:
            - Path=${app.api-prefix}/admin/users/**, ${app.api-prefix}/users/**
          filters:
            - StripPrefix=2

        - id: account-service
          uri: http://localhost:5004
          predicates:
            - Path=${app.api-prefix}/account/**
          filters:
            - StripPrefix=2

        - id: permission-service
          uri: http://localhost:5004
          predicates:
            - Path=${app.api-prefix}/admin/permissions/**
          filters:
            - StripPrefix=2

        - id: role-service
          uri: http://localhost:5004
          predicates:
            - Path=${app.api-prefix}/admin/roles/**
          filters:
            - StripPrefix=2

        - id: notification-service
          uri: http://localhost:5004
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2

        - id: file-service
          uri: http://localhost:5004
          predicates:
            - Path=${app.api-prefix}/internal/files/**
          filters:
            - StripPrefix=2

        - id: doctor-service
          uri: http://localhost:5001
          predicates:
            - Path=${app.api-prefix}/doctors/**
          filters:
            - StripPrefix=2
