spring:
  application:
    name: workSchedule-service
  datasource:
    url: jdbc:mysql://localhost:3306/workSchedule_service
    username: root
    password: root1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
  kafka:
    bootstrap-servers: localhost:9193
    consumer:
      group-id: workSchedule-service-group-v2
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.booking.infrastructure.kafka.event  # Hoặc batch nếu bạn muốn batch consume
server:
  port: 5006
  error:
    include-stacktrace: never

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#jwt:
#  expiration: 2592000
#  expiration-refresh-token: 5184000
#  secretkey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
#
#api:
#  prefix: /api/v1


