spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: root1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
  kafka:
    bootstrap-servers: localhost:9193  # địa chỉ Kafka broker
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  mail:
    host: smtp.gmail.com
    port: 587
    username: tmvvu1252@gmail.com
    password: tpfb vnwu hvaa wpag
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

server:
  port: 5004
  error:
    include-stacktrace: never

jwt:
  expiration: 2592000
  expiration-refresh-token: 5184000
  secretkey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=

api:
  prefix: /api/v1

 # Đảm bảo đường dẫn này trùng với Swagger UI của bạn

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
logging:
  level:
    org.springframework.web: DEBUG
    com.booking.controller.http.user: DEBUG
    com.booking: DEBUG
