spring:
  application:
    name: doctor-service
  datasource:
    url: jdbc:mysql://localhost:3306/doctor_service
    username: root
    password: root1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: doctor-service-group-v2
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.core.DefaultKafkaProducerFactory
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.core.JsonDeserializer
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer

      listener:
      ack-mode: record   # Hoặc batch nếu bạn muốn batch consume
      type: single       # Hoặc batch nếu batch consume
server:
  port: 5001
  error:
    include-stacktrace: never

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#jwt:
#  expiration: 2592000
#  expiration-refresh-token: 5184000
#  secretkey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
#
#api:
#  prefix: /api/v1


